apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
spec:
  selector:
    matchLabels:
      app: student-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: student-mysql
    spec:
      containers:
        - name: student-system-container
          image: gekoline/student-system:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: student-service
spec:
  selector:
    app: student-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
